# Generated by Django 4.1.5 on 2023-01-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='things',
            options={'verbose_name_plural': 'Things'},
        ),
    ]
